splitter:
  splits_folder: DATA_SPLITS
  class_name: mlwiz.data.splitter.Splitter
  args:
    n_outer_folds: 1
    n_inner_folds: 1
    seed: 42
    stratify: False
    shuffle: False
    inner_val_ratio: 0.1
    outer_val_ratio: 0.1
    test_ratio: 0.166666666667
dataset:
  class_name: dataset.PermutedMNIST
  args:
    storage_folder:  /mnt/local/ferrica/DATA/
